import {test,expect} from '@playwright/test'
import {openCase} from './support/harness'

test('a scoped field named name preserves slot selection and data',async({page})=>{
 await openCase(page,'named-scope')
 await expect(page.locator('[data-slot-state]')).toHaveText('closed')
 await page.locator('summary').click()
 await expect(page.locator('[data-slot-state]')).toHaveText('open')
})

for(const mode of ['vapor','interop'] as const){
 test(`${mode}: disclosure updates slot/model and forwards toggle once`,async({page})=>{
  await openCase(page,'disclosure',mode)
  await expect(page.locator('[data-ui=accordion][data-ui-part=root]')).toHaveCount(2)
  await expect(page.locator('summary[data-ui-part=trigger]')).toHaveCount(2)
  await expect(page.locator('[data-slot-state]').first()).toHaveText('closed')
  await page.locator('summary').first().click()
  await expect(page.locator('[data-slot-state]').first()).toHaveText('open')
  await expect(page.locator('[data-model]')).toHaveText('true')
  await expect(page.locator('[data-toggles]')).toHaveText('1')
 })
}
test('native grouping updates both disclosures',async({page})=>{
 await openCase(page,'disclosure')
 await page.locator('summary').first().click()
 await expect(page.locator('[data-slot-state]').first()).toHaveText('open')
 await page.locator('summary').nth(1).click()
 await expect(page.locator('[data-slot-state]').first()).toHaveText('closed')
 await expect(page.locator('[data-slot-state]').nth(1)).toHaveText('open')
})
test('unrelated parent update preserves local edits; mapped prop changes synchronize',async({page})=>{
 await openCase(page,'uncontrolled')
 await page.locator('summary').click()
 await expect(page.locator('[data-slot-state]')).toHaveText('open')
 await page.locator('[data-action=name]').click()
 await expect(page.locator('[data-slot-state]')).toHaveText('open')
 await page.locator('[data-action=open]').click()
 await expect(page.locator('details')).toHaveJSProperty('open',true)
 await page.locator('[data-action=open]').click()
 await expect(page.locator('details')).toHaveJSProperty('open',false)
})
test('checkbox forwards original input/change exactly once and preserves reset baseline',async({page})=>{
 await openCase(page,'checkbox')
 await page.locator('input').check()
 await expect(page.locator('[data-model]')).toHaveText('true')
 await expect(page.locator('[data-events]')).toHaveText('input:INPUT,change:INPUT')
 await page.locator('[data-action=reset]').click()
 await expect(page.locator('input')).not.toBeChecked()
 await expect(page.locator('[data-model]')).toHaveText('false')
})
test('text edits, later props, and reset keep initial baseline',async({page})=>{
 await openCase(page,'text')
 await page.locator('input').fill('edited')
 await expect(page.locator('[data-slot-state]')).toHaveText('edited')
 await page.locator('[data-action=parent]').click()
 await expect(page.locator('input')).toHaveValue('parent')
 await page.locator('[data-action=reset]').click()
 await expect(page.locator('input')).toHaveValue('initial')
 await expect(page.locator('[data-model]')).toHaveText('initial')
})
test('canceled reset leaves native value and state unchanged',async({page})=>{
 await openCase(page,'text')
 await page.locator('input').fill('edited')
 await page.locator('[data-action=cancel]').click()
 await page.locator('[data-action=reset]').click()
 await expect(page.locator('input')).toHaveValue('edited')
 await expect(page.locator('[data-model]')).toHaveText('edited')
})
test('numeric clear retains native NaN',async({page})=>{
 await openCase(page,'number')
 await page.locator('input').fill('')
 await expect(page.locator('[data-model]')).toHaveText('NaN')
 await expect(page.locator('[data-slot-state]')).toHaveText('NaN')
})
test('range constraints precede value initialization and state uses sanitized DOM value',async({page})=>{
 await openCase(page,'range')
 await expect(page.locator('input')).toHaveValue('20')
 await expect(page.locator('[data-model]')).toHaveText('20')
})
test('changed range constraints synchronize the sanitized native value',async({page})=>{
 await openCase(page,'range')
 await page.locator('[data-action=max]').click()
 await expect(page.locator('input')).toHaveValue('14')
 await expect(page.locator('[data-model]')).toHaveText('14')
})
test('native form reassociation updates reset subscriptions',async({page})=>{
 await openCase(page,'reassociate')
 await page.locator('input').fill('edited')
 await page.locator('[data-action=associate]').click()
 await page.locator('[data-action=reset-second]').click()
 await expect(page.locator('input')).toHaveValue('initial')
 await expect(page.locator('[data-model]')).toHaveText('initial')
})
test('queued reset work does not emit after unmount',async({page})=>{
 await openCase(page,'text')
 await page.locator('input').fill('edited')
 await page.locator('[data-action=dispose]').click()
 await expect(page.locator('input')).toHaveCount(0)
 await expect(page.locator('[data-model]')).toHaveText('edited')
})
test('a descendant-originating event reads the listener node',async({page})=>{
 await openCase(page,'disclosure')
 await page.locator('summary').first().evaluate(summary=>{
  const child=summary.appendChild(document.createElement('span'))
  Object.assign(child,{open:true})
  child.dispatchEvent(new Event('toggle',{bubbles:true}))
 })
 await expect(page.locator('[data-model]')).toHaveText('false')
 await expect(page.locator('[data-slot-state]').first()).toHaveText('closed')
 await expect(page.locator('[data-toggles]')).toHaveText('1')
})
test('absent optional bindings do not serialize undefined',async({page})=>{
 await openCase(page,'text')
 await expect(page.locator('input')).not.toHaveAttribute('name')
 await expect(page.locator('input')).not.toHaveAttribute('min')
 await expect(page.locator('input')).not.toHaveAttribute('form')
})
